import { useState, type ReactNode } from 'react';
import { ArrowRight, BarChart3, Check, Compass, Moon, Sparkles, Sun } from 'lucide-react';
import './_group.css';

function Logo({ light = false }: { light?: boolean }) {
  return <a href="#" className={`focus-ring inline-flex items-center gap-3 ${light ? 'text-[#f8f4e8]' : 'text-[#202840]'}`}>
    <span className="grid size-9 place-items-center rounded-xl bg-[#d9ef66] text-[#202840] shadow-[4px_4px_0_#202840]"><Compass size={20} strokeWidth={2.5} /></span>
    <span className="display text-[19px] font-bold tracking-[-0.04em]">Decision<span className={light ? 'text-[#d9ef66]' : 'text-[#0f766e]'}>Intel</span></span>
  </a>;
}

function ThemeToggle() {
  const [dark, setDark] = useState(false);
  return <button type="button" onClick={() => setDark(!dark)} className="theme-toggle focus-ring inline-flex size-10 items-center justify-center rounded-xl border border-[#c9c1ae] bg-[#f8f4e8] text-[#202840] shadow-sm" aria-label="Toggle theme">{dark ? <Sun size={17} /> : <Moon size={17} />}</button>;
}

function PublicNav() {
  return <header className="mx-auto flex w-full max-w-7xl items-center justify-between px-5 py-6 lg:px-10">
    <Logo />
    <nav className="hidden items-center gap-8 text-sm font-semibold text-[#556075] md:flex" aria-label="Main navigation">
      <a className="focus-ring transition-colors hover:text-[#0f766e]" href="#method">How it works</a><a className="focus-ring transition-colors hover:text-[#0f766e]" href="#evidence">The evidence</a><a className="focus-ring transition-colors hover:text-[#0f766e]" href="#teams">For teams</a><a className="focus-ring transition-colors hover:text-[#0f766e]" href="#api">API</a>
    </nav>
    <div className="flex items-center gap-2"><ThemeToggle /><a href="#sign-in" className="focus-ring hidden rounded-xl px-4 py-2.5 text-sm font-bold text-[#556075] hover:text-[#0f766e] sm:inline-flex">Sign in</a><a href="#guest" className="focus-ring hidden rounded-xl px-4 py-2.5 text-sm font-bold text-[#556075] hover:text-[#0f766e] sm:inline-flex">Try as guest</a><a href="#start" className="focus-ring inline-flex items-center gap-2 rounded-xl bg-[#202840] px-4 py-2.5 text-sm font-bold text-[#f8f4e8] shadow-[3px_3px_0_#d9ef66]">Start comparing <ArrowRight size={16} /></a></div>
  </header>;
}

function FeatureComparisonTile({ compact = false }: { compact?: boolean }) {
  return <div className={`relative overflow-hidden rounded-2xl border border-[#9fb671] bg-[#e8f2bd] ${compact ? 'p-5' : 'p-6 sm:p-7'}`}>
    <div className="absolute -right-8 -top-8 size-28 rounded-full border-[18px] border-[#d9ef66]/70" /><div className="relative"><div className="flex items-center gap-2 text-[#0f766e]"><span className="grid size-8 place-items-center rounded-lg bg-[#0f766e] text-[#d9ef66]"><BarChart3 size={16} /></span><span className="mono text-[10px] font-bold uppercase tracking-[.16em]">Feature-by-feature product comparison</span></div><h3 className={`display font-bold tracking-[-.035em] text-[#202840] ${compact ? 'mt-4 text-xl' : 'mt-5 text-2xl'}`}>Compare the actual product, not just the brand.</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-[#566074]">See exact features, measurable specifications, price and material omissions side by side—from EV range, charging and safety to card rates and rewards, loan fees and eligibility, or software plan limits.</p></div>
  </div>;
}

function LinkButton({ children, href = '#start' }: { children: ReactNode; href?: string }) {
  return <a href={href} className="focus-ring inline-flex items-center gap-3 rounded-xl bg-[#0f766e] px-6 py-3.5 text-sm font-bold text-[#f8f4e8] shadow-[4px_4px_0_#202840] transition-transform hover:-translate-y-0.5">{children}</a>;
}

export function Current() {
  return <main className="landing-page grain min-h-[100dvh] overflow-hidden bg-[#f2eee2]">
    <PublicNav />
    <section className="relative mx-auto grid max-w-7xl items-center gap-16 px-5 pb-24 pt-14 lg:grid-cols-[1.03fr_.97fr] lg:px-10 lg:pb-32 lg:pt-20">
      <div className="absolute -left-40 top-20 size-[420px] rounded-full bg-[#e2efaa]/50 blur-3xl" /><div className="relative z-10 animate-rise">
        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-[#c8d99a] bg-[#e8f2bd] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] text-[#35665c]"><span className="size-2 rounded-full bg-[#0f766e]" /> AI-powered decision intelligence</div>
        <h1 className="landing-hero-title max-w-3xl text-[clamp(3rem,7vw,5rem)] font-bold leading-[.98] tracking-[-.065em] text-[#202840]"><span className="block">Make the call</span><span className="landing-hero-accent block text-[#0f766e]">before the meeting.</span></h1>
        <p className="mt-8 max-w-xl text-lg leading-8 text-[#556075]">DecisionIntel turns a messy buying question into a defensible shortlist—with the evidence, trade-offs, and recommendation in one place.</p>
        <div className="mt-9 flex flex-wrap items-center gap-4"><LinkButton>Start a comparison <ArrowRight size={17} /></LinkButton><a href="#guest" className="text-xs font-semibold text-[#8a8b8b] hover:text-[#0f766e]">Try one comparison without signing up</a></div>
        <div className="mt-14 flex items-center gap-4 text-xs text-[#687083]"><div className="flex -space-x-2">{['MC','JR','SL','AK'].map((x, i) => <span key={x} className={`grid size-8 place-items-center rounded-full border-2 border-[#f2eee2] text-[10px] font-bold text-[#f8f4e8] ${['bg-[#0f766e]','bg-[#b94d45]','bg-[#7d6b8d]','bg-[#cf9147]'][i]}`}>{x}</span>)}</div><span><strong className="text-[#202840]">2,400+ teams</strong> are making sharper calls</span></div>
      </div>
      <div className="relative animate-rise animate-rise-1"><div className="absolute -right-8 -top-8 z-20 hidden rotate-6 rounded-xl border border-[#202840]/10 bg-[#d9ef66] px-4 py-2 text-xs font-bold text-[#202840] shadow-[4px_4px_0_#202840] sm:block">THE SHORTLIST, FINALLY</div><div className="relative overflow-hidden rounded-[2rem] border border-[#202840] bg-[#202840] p-3 shadow-[10px_10px_0_#d9ef66]"><div className="rounded-[1.4rem] bg-[#e7e2d4] p-5 sm:p-7"><div className="mb-7 flex items-center justify-between"><div><p className="mono text-[9px] uppercase tracking-[.18em] text-[#788080]">New workspace / 024</p><p className="display mt-2 text-2xl font-bold text-[#202840]">Your question, clarified</p></div><div className="grid size-10 place-items-center rounded-xl bg-[#0f766e] text-[#d9ef66]"><Sparkles size={18} /></div></div><div className="rounded-2xl border border-[#d0c8b7] bg-[#f8f4e8] p-4"><p className="text-sm leading-6 text-[#4c576b]">“We’re a 40-person product team looking for a project tool with great async rituals, clear roadmaps, and sane pricing.”</p><div className="mt-4 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#0f766e]"><Check size={13} /> Prompt parsed</div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-[#d0c8b7] bg-[#f8f4e8] p-4"><p className="mono text-[9px] uppercase tracking-[.12em] text-[#8b8a80]">Vendors</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-md bg-[#dcefe9] px-2 py-1 text-xs font-bold text-[#0f766e]">Linear</span><span className="rounded-md bg-[#eee2c7] px-2 py-1 text-xs font-bold text-[#8c6328]">Asana</span><span className="rounded-md bg-[#e5dce8] px-2 py-1 text-xs font-bold text-[#685474]">Height</span></div></div><div className="rounded-2xl border border-[#d0c8b7] bg-[#f8f4e8] p-4"><p className="mono text-[9px] uppercase tracking-[.12em] text-[#8b8a80]">Fit score</p><div className="mt-3 flex items-end gap-1"><span className="display text-4xl font-bold text-[#0f766e]">86</span><span className="mb-1 text-xs font-bold text-[#7a7b76]">/ 100</span></div></div></div><div className="mt-4 rounded-2xl bg-[#0f766e] p-4 text-[#f8f4e8]"><p className="mono text-[9px] uppercase tracking-[.12em] text-[#acd9ce]">Recommendation</p><div className="mt-2 flex items-center justify-between"><p className="display text-xl font-bold">Linear</p><span className="rounded-full bg-[#d9ef66] px-2 py-1 text-[10px] font-bold text-[#202840]">Strong fit</span></div><p className="mt-2 text-xs leading-5 text-[#d1e6df]">Best match for your team’s async operating rhythm.</p></div></div></div></div>
    </section>
    <section id="method" className="border-y border-[#d8d0bd] bg-[#e7e2d4] px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mono text-xs font-bold uppercase tracking-[.2em] text-[#0f766e]">A better starting point</p><h2 className="display mt-4 text-4xl font-bold leading-tight tracking-[-.045em] text-[#202840] sm:text-5xl">Good research starts with a better question.</h2></div><div className="grid gap-8 sm:grid-cols-3">{[['01','Say it plainly','Start with the messy version. We’ll find the shape inside it.'],['02','See the trade-offs','Scores, sources, and the “why” behind every recommendation.'],['03','Move with confidence','Bring a decision to the room, not another tab to review.']].map(([n,t,x]) => <div key={n} className="border-t-2 border-[#202840] pt-4"><span className="mono text-xs font-bold text-[#0f766e]">{n}</span><h3 className="display mt-8 text-xl font-bold text-[#202840]">{t}</h3><p className="mt-3 text-sm leading-6 text-[#667083]">{x}</p></div>)}</div></div><div className="mt-12"><FeatureComparisonTile /></div></div></section>
    <section id="evidence" className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-10"><div><p className="mono text-xs font-bold uppercase tracking-[.2em] text-[#b94d45]">The evidence</p><h2 className="display mt-4 max-w-2xl text-5xl font-bold leading-[.94] tracking-[-.055em] text-[#202840]">Less “it depends.”<br /><span className="text-[#b94d45]">More “here’s why.”</span></h2><p className="mt-7 max-w-lg text-base leading-7 text-[#667083]">The workspace keeps evidence and judgment together. Compare how vendors perform against the criteria your team actually cares about, then share the reasoning—not just the winner.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full border border-[#c9c1ae] px-3 py-2 text-xs font-bold text-[#556075]">Pricing clarity</span><span className="rounded-full border border-[#c9c1ae] px-3 py-2 text-xs font-bold text-[#556075]">Feature fit</span><span className="rounded-full border border-[#c9c1ae] px-3 py-2 text-xs font-bold text-[#556075]">Team context</span></div></div><div className="relative rounded-[2rem] bg-[#202840] p-7 text-[#f8f4e8] shadow-[8px_8px_0_#d9ef66]"><div className="absolute right-6 top-6 grid size-11 place-items-center rounded-full border border-[#68738e] text-[#d9ef66]"><BarChart3 size={19} /></div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#a5b0c7]">Example scorecard</p><div className="mt-12 space-y-5">{[['Fit for team size',92,'#d9ef66'],['Pricing transparency',81,'#db8a52'],['Workflow flexibility',74,'#8bc9bb']].map(([l,s,c]) => <div key={l as string}><div className="flex justify-between text-sm font-semibold"><span>{l}</span><span className="mono text-xs">{s}</span></div><div className="mt-2 h-2 rounded-full bg-[#3b4662]"><div className="h-2 rounded-full" style={{ width: `${s}%`, backgroundColor: c as string }} /></div></div>)}</div><div className="mt-10 border-t border-[#3b4662] pt-5 text-sm leading-6 text-[#cad0dc]">“Linear is the strongest fit—not because it has the most features, but because it creates the least operational drag for this team.”</div></div></section>
    <section id="teams" className="bg-[#d9ef66] px-5 py-20 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="mono text-xs font-bold uppercase tracking-[.2em] text-[#55715e]">For teams who decide</p><h2 className="display mt-3 max-w-2xl text-4xl font-bold leading-tight tracking-[-.05em] text-[#202840]">The best choice is the one everyone can explain.</h2></div><LinkButton>Open your workspace <ArrowRight size={17} /></LinkButton></div></section>
    <footer className="bg-[#202840] px-5 py-8 text-[#c4cada] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><Logo light /><p className="text-xs">Research with fewer tabs. Decide with fewer caveats.</p><p className="mono text-[10px] uppercase tracking-[.14em] text-[#8791a8]">© 2025 VC / built for clear calls</p></div></footer>
  </main>;
}